### ISSUE TITLE
Añadir import

### ISSUE THREAD

**Issue by Miangame** [jponferrada26/CONCESIONARIO_COCHES-GUI#1]
Por qué no añades un import.java.utils en lugar de poner lo de esta línea y así no se ve tan "feo"?
https://github.com/jponferrada26/CONCESIONARIO_COCHES-GUI/blob/master/concesionarioCochesGUI/src/concesionarioCochesGUI/gui/BuscarPorColor.java#L23

**Comment by jponferrada26** [comment]
Es cierto. Lo cambio :)
